# Generated by Django 4.1 on 2023-10-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('title', models.CharField(default='Lesson X', max_length=200)),
                ('description', models.TextField(default='Enter description')),
                ('vimeo_id', models.CharField(default='000000000', max_length=30)),
                ('secondary_vimeo_id', models.CharField(default='999999999999', max_length=30)),
                ('length', models.IntegerField(default=5)),
                ('thumbnail_id', models.IntegerField(default=100)),
                ('has_file', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
