# Generated by Django 4.1 on 2023-11-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='secondary_vimeo_id',
        ),
    ]
